"""Auto-generated documentation for a source: a data dictionary, a relationship list, and
a Mermaid relationship map. Built only from the metadata store (no database queries).

Output (default ``generated_docs/<source>/``):
- ``README.md``          overview + relationship map (Mermaid)
- ``data_dictionary.md`` every table: rows, keys, columns, measurements, links in/out
- ``relationships.md``   every relationship with kind, status, confidence and evidence
"""

import re
import uuid
from dataclasses import dataclass
from pathlib import Path

from sqlalchemy.orm import Session

from ai_data_engineer.discovery.catalog import Catalog, TableInfo, load_catalog
from ai_data_engineer.discovery.store import current_relationships
from ai_data_engineer.graph.models import (
    DataSource,
    Relationship,
    RelationshipKind,
    RelationshipStatus,
)
from ai_data_engineer.graph.queries import get_column_profile_history

DEFAULT_DOCS_DIR = Path("generated_docs")
MAX_TOP_VALUES_SHOWN = 5


@dataclass(frozen=True)
class Link:
    child: TableInfo
    child_columns: tuple[str, ...]
    parent: TableInfo
    parent_columns: tuple[str, ...]
    rel: Relationship

    @property
    def label(self) -> str:
        cols = ", ".join(self.child_columns)
        if self.rel.kind is RelationshipKind.DECLARED:
            return f"{cols} (declared FK)"
        conf = f"{self.rel.confidence:.2f}" if self.rel.confidence is not None else "?"
        return f"{cols} (inferred {conf}, {self.rel.status.value})"


def generate_docs(
    session: Session, source: DataSource, out_root: Path = DEFAULT_DOCS_DIR
) -> list[Path]:
    catalog = load_catalog(session, source)
    links = _links(session, catalog)
    out = out_root / source.name
    out.mkdir(parents=True, exist_ok=True)
    files = {
        "README.md": _overview(catalog, links),
        "data_dictionary.md": _dictionary(session, catalog, links),
        "relationships.md": _relationships(links),
    }
    paths = []
    for name, content in files.items():
        path = out / name
        path.write_text(content, encoding="utf-8")
        paths.append(path)
    return paths


def _links(session: Session, catalog: Catalog) -> list[Link]:
    names = {
        column.column_key: (table, column.name)
        for table in catalog.tables.values()
        for column in table.columns.values()
    }
    links = []
    for rel in current_relationships(session, catalog):
        if rel.status is RelationshipStatus.REJECTED:
            continue
        pairs = [(names.get(c.from_column_key), names.get(c.to_column_key)) for c in rel.columns]
        resolved = [(f, t) for f, t in pairs if f is not None and t is not None]
        if not resolved or len(resolved) != len(pairs):
            continue
        links.append(
            Link(
                child=resolved[0][0][0],
                child_columns=tuple(f[1] for f, _ in resolved),
                parent=resolved[0][1][0],
                parent_columns=tuple(t[1] for _, t in resolved),
                rel=rel,
            )
        )
    return sorted(links, key=lambda link: (link.child.ref, link.child_columns))


def _overview(catalog: Catalog, links: list[Link]) -> str:
    declared = sum(link.rel.kind is RelationshipKind.DECLARED for link in links)
    inferred = len(links) - declared
    out = [
        f"# {catalog.source.name}: generated documentation",
        "",
        "*Generated by AI Data Engineer from the latest scan. Inferred relationships are "
        "evidence-based proposals; review them with `aide relationships`.*",
        "",
        f"- **Tables:** {len(catalog.tables)}",
        f"- **Relationships:** {len(links)} ({declared} declared foreign keys, "
        f"{inferred} inferred and not declared in the database)",
        "- [Data dictionary](data_dictionary.md) · [Relationships](relationships.md)",
        "",
        "## Relationship map",
        "",
        "Solid lines are declared foreign keys; dotted lines are inferred.",
        "",
        "```mermaid",
        "erDiagram",
    ]
    linked = {t.ref for link in links for t in (link.child, link.parent)}
    for table in sorted(catalog.tables.values(), key=lambda t: t.ref):
        if table.ref not in linked:
            continue
        out.append(f"    {_entity(table)} {{")
        keyed = {c for link in links if link.child is table for c in link.child_columns}
        for column in table.columns.values():
            if column.name in table.primary_key or column.name in keyed:
                marker = " PK" if column.name in table.primary_key else " FK"
                out.append(f"        {column.family.value} {_attr(column.name)}{marker}")
        out.append("    }")
    for link in links:
        line = "--" if link.rel.kind is RelationshipKind.DECLARED else ".."
        out.append(f'    {_entity(link.parent)} ||{line}o{{ {_entity(link.child)} : "{link.label}"')
    out += ["```", ""]
    return "\n".join(out)


def _dictionary(session: Session, catalog: Catalog, links: list[Link]) -> str:
    out = [f"# {catalog.source.name}: data dictionary", ""]
    for table in sorted(catalog.tables.values(), key=lambda t: t.ref):
        rows = f"{table.estimated_rows:,}" if table.estimated_rows is not None else "?"
        pk = ", ".join(table.primary_key) or "**none**"
        out += [
            f"## `{table.ref}`",
            "",
            f"- **Rows (latest scan):** {rows}",
            f"- **Primary key:** {pk}",
        ]
        outgoing = [link for link in links if link.child is table]
        incoming = [link for link in links if link.parent is table]
        refs = ", ".join(f"`{link.parent.ref}` via {link.label}" for link in outgoing)
        referenced_by = ", ".join(f"`{link.child.ref}` via {link.label}" for link in incoming)
        out += [
            "- **References:** " + (refs or "none"),
            "- **Referenced by:** " + (referenced_by or "none"),
            "",
            "| Column | Type | Has nulls | Null % | Distinct | Top values |",
            "|---|---|---|---|---|---|",
        ]
        for column in table.columns.values():
            null_pct = (
                f"{column.null_count / column.row_count:.1%}"
                if column.row_count and column.null_count is not None
                else "-"
            )
            distinct = f"{column.distinct_count:,}" if column.distinct_count is not None else "-"
            out.append(
                f"| {column.name} | {column.native_type} | "
                f"{'yes' if column.null_count else 'no'} | {null_pct} | {distinct} | "
                f"{_top_values(session, column.column_key)} |"
            )
        out.append("")
    return "\n".join(out)


def _relationships(links: list[Link]) -> str:
    out = [
        "# Relationships",
        "",
        "| From | To | Kind | Status | Confidence | Signals | Why |",
        "|---|---|---|---|---|---|---|",
    ]
    for link in links:
        reasons = "; ".join(link.rel.evidence.get("reasons", [])) or link.rel.evidence.get(
            "constraint", ""
        )
        conf = f"{link.rel.confidence:.2f}" if link.rel.confidence is not None else "-"
        out.append(
            f"| `{link.child.ref}({', '.join(link.child_columns)})` | "
            f"`{link.parent.ref}({', '.join(link.parent_columns)})` | {link.rel.kind.value} | "
            f"{link.rel.status.value} | {conf} | {', '.join(link.rel.signals)} | {reasons} |"
        )
    return "\n".join(out) + "\n"


def _top_values(session: Session, column_key: uuid.UUID) -> str:
    profile = get_column_profile_history(session, column_key, limit=1)
    if not profile or not profile[0].top_values:
        return ""
    shown = profile[0].top_values[:MAX_TOP_VALUES_SHOWN]
    return ", ".join(f"`{v['value']}` ({v['count']})" for v in shown)


def _entity(table: TableInfo) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", f"{table.schema_name}_{table.name}")


def _attr(name: str) -> str:
    return re.sub(r"[^A-Za-z0-9_]", "_", name)
