-- Creates the scoped read-only role, a small auto-suspending warehouse, and the
-- key-pair service user the platform connects as.
-- Run in Snowsight as ACCOUNTADMIN. Replace JAFFLE_DB and PASTE_PUBLIC_KEY_HERE.
-- This is also the template for the customer onboarding script (Stage 3).

USE ROLE ACCOUNTADMIN;

CREATE ROLE IF NOT EXISTS AIDE_READONLY;

CREATE WAREHOUSE IF NOT EXISTS AIDE_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;
GRANT USAGE ON WAREHOUSE AIDE_WH TO ROLE AIDE_READONLY;

GRANT USAGE ON DATABASE JAFFLE_DB TO ROLE AIDE_READONLY;
GRANT USAGE ON ALL SCHEMAS IN DATABASE JAFFLE_DB TO ROLE AIDE_READONLY;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE JAFFLE_DB TO ROLE AIDE_READONLY;
GRANT SELECT ON ALL TABLES IN DATABASE JAFFLE_DB TO ROLE AIDE_READONLY;
GRANT SELECT ON FUTURE TABLES IN DATABASE JAFFLE_DB TO ROLE AIDE_READONLY;
GRANT SELECT ON ALL VIEWS IN DATABASE JAFFLE_DB TO ROLE AIDE_READONLY;
GRANT SELECT ON FUTURE VIEWS IN DATABASE JAFFLE_DB TO ROLE AIDE_READONLY;

-- Query history / usage metadata (tighter than IMPORTED PRIVILEGES).
GRANT DATABASE ROLE SNOWFLAKE.USAGE_VIEWER TO ROLE AIDE_READONLY;
-- Fallback only if something needed isn't visible:
-- GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE AIDE_READONLY;

-- Public key body only: the text between the BEGIN/END lines, joined into one line.
CREATE USER IF NOT EXISTS AIDE_SVC
  TYPE = SERVICE
  DEFAULT_ROLE = AIDE_READONLY
  DEFAULT_WAREHOUSE = AIDE_WH
  RSA_PUBLIC_KEY = 'PASTE_PUBLIC_KEY_HERE';
GRANT ROLE AIDE_READONLY TO USER AIDE_SVC;
